[env:pico2]
platform = file://platform-raspberrypi
board = rpipico2
framework = arduino
board_build.core = earlephilhower
board_build.framework_dir = frameworks/framework-arduino-pico

lib_deps =
    micro_ros_platformio
    Time

lib_ldf_mode = chain+


